name: Run Terraform Plan

# workflow should only run on pull requests.
on:
  pull_request:

env:
  AWS_REGION: us-east-1

jobs:
  terraform-environments:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "::set-output name=matrix::`cat environments-to-provision.json | tr -d '\n '`"
  cleanup-old-comments:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: kanga333/comment-hider@v0.3.0
        name: Hide bot comments
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  terraform-plan:
    needs:
      - terraform-environments
      - cleanup-old-comments
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    strategy:
      matrix: ${{ fromJSON(needs.terraform-environments.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v3
        with:
          repository: the-mom-project/terraform-github-actions
          ref: main
          token: ${{ secrets.GITHUBCOM_READ_ONLY }} # Developer PAT to access other private repos
          path: .github/actions/terraform-actions

      - name: Set Git Config
        run: |
          git config --global url."https://oauth2:${{ secrets.GITHUBCOM_READ_ONLY }}@github.com".insteadOf ssh://git@github.com

      - name: terraform plan
        uses: ./.github/actions/terraform-actions/terraform-plan
        with:
          aws_role: ${{ secrets.AWS_DEPLOY_ARN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ matrix.environment }}